export const currencies = [
  { country: "Afghanistan", currencyName: "Afghan Afghani", code: "AFN" },
  { country: "Albania", currencyName: "Albanian Lek", code: "ALL" },
  { country: "Algeria", currencyName: "Algerian Dinar", code: "DZD" },
  { country: "Angola", currencyName: "Angolan Kwanza", code: "AOA" },
  { country: "Argentina", currencyName: "Argentine Peso", code: "ARS" },
  { country: "Armenia", currencyName: "Armenian Dram", code: "AMD" },
  { country: "Australia", currencyName: "Australian Dollar", code: "AUD" },
  { country: "Azerbaijan", currencyName: "Azerbaijani Manat", code: "AZN" },
  { country: "Bahamas", currencyName: "Bahamian Dollar", code: "BSD" },
  { country: "Bangladesh", currencyName: "Bangladeshi Taka", code: "BDT" },
  { country: "Barbados", currencyName: "Barbadian Dollar", code: "BBD" },
  { country: "Belarus", currencyName: "Belarusian Ruble", code: "BYN" },
  { country: "Belize", currencyName: "Belize Dollar", code: "BZD" },
  { country: "Bolivia", currencyName: "Bolivian Boliviano", code: "BOB" },
  {
    country: "Bosnia and Herzegovina",
    currencyName: "Bosnian Convertible Mark",
    code: "BAM",
  },
  { country: "Botswana", currencyName: "Botswanan Pula", code: "BWP" },
  { country: "Brazil", currencyName: "Brazilian Real", code: "BRL" },
  { country: "Brunei", currencyName: "Brunei Dollar", code: "BND" },
  { country: "Bulgaria", currencyName: "Bulgarian Lev", code: "BGN" },
  { country: "Cambodia", currencyName: "Cambodian Riel", code: "KHR" },
  { country: "Canada", currencyName: "Canadian Dollar", code: "CAD" },
  { country: "Chile", currencyName: "Chilean Peso", code: "CLP" },
  { country: "China", currencyName: "Chinese Yuan", code: "CNY" },
  { country: "Colombia", currencyName: "Colombian Peso", code: "COP" },
  { country: "Costa Rica", currencyName: "Costa Rican Colón", code: "CRC" },
  { country: "Croatia", currencyName: "Croatian Kuna", code: "HRK" }, // Note: Croatia uses EUR since 2023, but keeping for completeness
  { country: "Cuba", currencyName: "Cuban Peso", code: "CUP" },
  { country: "Czech Republic", currencyName: "Czech Koruna", code: "CZK" },
  { country: "Denmark", currencyName: "Danish Krone", code: "DKK" },
  {
    country: "Dominican Republic",
    currencyName: "Dominican Peso",
    code: "DOP",
  },
  { country: "Egypt", currencyName: "Egyptian Pound", code: "EGP" },
  {
    country: "Eurozone (e.g., Germany, France, Italy)",
    currencyName: "Euro",
    code: "EUR",
  },
  { country: "Fiji", currencyName: "Fijian Dollar", code: "FJD" },
  { country: "Georgia", currencyName: "Georgian Lari", code: "GEL" },
  { country: "Ghana", currencyName: "Ghanaian Cedi", code: "GHS" },
  { country: "Guatemala", currencyName: "Guatemalan Quetzal", code: "GTQ" },
  { country: "Honduras", currencyName: "Honduran Lempira", code: "HNL" },
  { country: "Hong Kong", currencyName: "Hong Kong Dollar", code: "HKD" },
  { country: "Hungary", currencyName: "Hungarian Forint", code: "HUF" },
  { country: "Iceland", currencyName: "Icelandic Króna", code: "ISK" },
  { country: "India", currencyName: "Indian Rupee", code: "INR" },
  { country: "Indonesia", currencyName: "Indonesian Rupiah", code: "IDR" },
  { country: "Iran", currencyName: "Iranian Rial", code: "IRR" },
  { country: "Iraq", currencyName: "Iraqi Dinar", code: "IQD" },
  { country: "Israel", currencyName: "Israeli New Shekel", code: "ILS" },
  { country: "Jamaica", currencyName: "Jamaican Dollar", code: "JMD" },
  { country: "Japan", currencyName: "Japanese Yen", code: "JPY" },
  { country: "Jordan", currencyName: "Jordanian Dinar", code: "JOD" },
  { country: "Kazakhstan", currencyName: "Kazakhstani Tenge", code: "KZT" },
  { country: "Kenya", currencyName: "Kenyan Shilling", code: "KES" },
  { country: "Kuwait", currencyName: "Kuwaiti Dinar", code: "KWD" },
  { country: "Lebanon", currencyName: "Lebanese Pound", code: "LBP" },
  { country: "Malaysia", currencyName: "Malaysian Ringgit", code: "MYR" },
  { country: "Mexico", currencyName: "Mexican Peso", code: "MXN" },
  { country: "Morocco", currencyName: "Moroccan Dirham", code: "MAD" },
  { country: "New Zealand", currencyName: "New Zealand Dollar", code: "NZD" },
  { country: "Nigeria", currencyName: "Nigerian Naira", code: "NGN" },
  { country: "Norway", currencyName: "Norwegian Krone", code: "NOK" },
  { country: "Pakistan", currencyName: "Pakistani Rupee", code: "PKR" },
  { country: "Peru", currencyName: "Peruvian Sol", code: "PEN" },
  { country: "Philippines", currencyName: "Philippine Peso", code: "PHP" },
  { country: "Poland", currencyName: "Polish Złoty", code: "PLN" },
  { country: "Qatar", currencyName: "Qatari Riyal", code: "QAR" },
  { country: "Romania", currencyName: "Romanian Leu", code: "RON" },
  { country: "Russia", currencyName: "Russian Ruble", code: "RUB" },
  { country: "Saudi Arabia", currencyName: "Saudi Riyal", code: "SAR" },
  { country: "Singapore", currencyName: "Singapore Dollar", code: "SGD" },
  { country: "South Africa", currencyName: "South African Rand", code: "ZAR" },
  { country: "South Korea", currencyName: "South Korean Won", code: "KRW" },
  { country: "Sri Lanka", currencyName: "Sri Lankan Rupee", code: "LKR" },
  { country: "Sweden", currencyName: "Swedish Krona", code: "SEK" },
  { country: "Switzerland", currencyName: "Swiss Franc", code: "CHF" },
  { country: "Taiwan", currencyName: "New Taiwan Dollar", code: "TWD" },
  { country: "Tanzania", currencyName: "Tanzanian Shilling", code: "TZS" },
  { country: "Thailand", currencyName: "Thai Baht", code: "THB" },
  { country: "Turkey", currencyName: "Turkish Lira", code: "TRY" },
  { country: "Ukraine", currencyName: "Ukrainian Hryvnia", code: "UAH" },
  { country: "United Arab Emirates", currencyName: "UAE Dirham", code: "AED" },
  {
    country: "United Kingdom",
    currencyName: "British Pound Sterling",
    code: "GBP",
  },
  {
    country: "United States",
    currencyName: "United States Dollar",
    code: "USD",
  },
  { country: "Vietnam", currencyName: "Vietnamese Đồng", code: "VND" },
  { country: "Zambia", currencyName: "Zambian Kwacha", code: "ZMW" },
];
